name: 'Dependabot Auto Approve and Merge'

description: 'Approve and auto-merge Dependabot PRs, or comment for major updates.'

inputs:
  pr-url:
    description: 'Pull request URL'
    required: true

  github-token:
    description: 'GitHub token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Dependabot metadata
      id: metadata
      uses: dependabot/fetch-metadata@v2
      with:
        github-token: ${{ inputs.github-token }}

    - name: '[Patch|Minor] Approve and auto-merge Dependabot PRs'
      if: steps.metadata.outputs.update-type == 'version-update:semver-patch' || steps.metadata.outputs.update-type == 'version-update:semver-minor'
      run: |
        gh pr review --approve "$PR_URL"
        gh pr merge --auto --merge "$PR_URL"
      shell: bash
      env:
        PR_URL: ${{ inputs.pr-url }}
        GITHUB_TOKEN: ${{ inputs.github-token }}

    - name: '[Major] Comment on major version updates'
      if: steps.metadata.outputs.update-type == 'version-update:semver-major'
      run: |
        gh pr comment "$PR_URL" --body "⚠️ This is a major version update. Please review manually before merging."
      shell: bash
      env:
        PR_URL: ${{ inputs.pr-url }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
